name: Molecule

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        scenario:
          - centos-systemd:stream9
          - debian-systemd:12
          - ubuntu-systemd:22.04
          - ubuntu-systemd:24.04
        python-version:
          - 3.12
        ansible-version:
          - 2.17.5

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ${{ github.repository }}/test-requirements.txt
      - name: Install ansible
        run: |
          python3 -m pip install ansible-core==${{ matrix.ansible-version }}
      - name: Install ansible collections
        run: |
          ansible-galaxy collection install -r ${{ github.repository }}/test-requirements.yml
      - name: Test with molecule
        run: |
          cd ${{ github.repository }}
          export docker_image_tag="${{ matrix.scenario }}"
          python3 -m molecule test
